### ISSUE TITLE
the snakemake running step throws `TypeError: must be str, not int`

### ISSUE THREAD

**Issue by dlaehnemann** [parklab/scan-snv#1]
I am trying to get scansnv to run on some data. I installed everything [via bioconda as described](https://github.com/parklab/scan-snv#installing-scan-snv). During the snakemake step it throws an error, so I went and ran only the snakemake command with `--debug` and `--verbose` enabled, namely:

```
snakemake --snakefile /path/to/conda/<hash_value>/lib/scansnv/Snakefile --configfile /path/to/out_dir/config.yaml --latency-wait 12 --rerun-incomplete --debug --verbose
```

This gives the following traceback that I cannot make any sense of:
```
Building DAG of jobs...
Full Traceback (most recent call last):
  File "/path/to/project/.snakemake/conda/<hash_value>/lib/python3.6/site-packages/snakemake/rules.py", line 540, in apply_input_function
    value = func(Wildcards(fromdict=wildcards), **_aux_params)
  File "/path/to/project/.snakemake/conda/<hash_value>/lib/scansnv/Snakefile", line 101, in <lambda>
    "    -out {output.vcf}"
TypeError: must be str, not int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/project/.snakemake/conda/<hash_value>/lib/python3.6/site-packages/snakemake/__init__.py", line 544, in snakemake
    export_cwl=export_cwl)
  File "/path/to/project/.snakemake/conda/<hash_value>/lib/python3.6/site-packages/snakemake/workflow.py", line 418, in execute
    dag.init()
  File "/path/to/project/.snakemake/conda/<hash_value>/lib/python3.6/site-packages/snakemake/dag.py", line 151, in init
    job.is_valid()
  File "/path/to/project/.snakemake/conda/<hash_value>/lib/python3.6/site-packages/snakemake/jobs.py", line 149, in is_valid
    self.rule.expand_params(self.wildcards_dict, self.input, self.output, resources)
  File "/path/to/project/.snakemake/conda/<hash_value>/lib/python3.6/site-packages/snakemake/rules.py", line 662, in expand_params
    "threads": resources._cores})
  File "/path/to/project/.snakemake/conda/<hash_value>/lib/python3.6/site-packages/snakemake/rules.py", line 564, in _apply_wildcards
    item = self.apply_input_function(item, wildcards, **aux_params)
  File "/path/to/project/.snakemake/conda/<hash_value>/lib/python3.6/site-packages/snakemake/rules.py", line 542, in apply_input_function
    raise InputFunctionException(e, rule=self, wildcards=wildcards)
snakemake.exceptions.InputFunctionException: TypeError: must be str, not int
Wildcards:
gatk_mmq=60
gatk_chunk=1

InputFunctionException in line 59 of /path/to/project/.snakemake/conda/<hash_value>/lib/scansnv/Snakefile:
TypeError: must be str, not int
Wildcards:
gatk_mmq=60
gatk_chunk=1
unlocking
removed all lock
```

The general setup is that I have one bam file for the bulk sample and multiple separate bam files for the single cell samples. I am not sure, as this is not documented anywhere, but I provided the `scansnv` command with each single cell bam file with a `--bam` flag invocation and a `--sc-sample` invocation. I.e. `--bam sc1 sc1.bam --bam sc2 sc2.bam [...] --sc-sample sc1 --sc-sample sc2 [...]`. I think this works, as the resulting `config.yaml` looks reasonable, namely something like this:

```
bams:
  bulk: /path/to/project/mapping/hg19/samples/bulk.sorted.bam
  sc1: /path/to/project/mapping/hg19/samples/sc1.sorted.bam
  sc2: /path/to/project/mapping/hg19/samples/sc2.sorted.bam
  ...
sc_samples:
  - sc1
  - sc2
  ...
bulk_sample: bulk
humref: /path/to/ref_data/hg19_CanonicalChr/genome_bwa-0.7.9a/hg19.fa
dbsnp: /path/to/ref_data/hg19_GATKBundle-2.8/dbsnp_138.hg19.vcf
shapeit_refpanel: /path/to/ref_data/hg19_shapeit/1000GP_Phase3
abmodel_chunks: 20
abmodel_samples_per_chunk: 1000
abmodel_hsnp_chunksize: 100
abmodel_steps: 4
fdr: 1.0
min_sc_alt: 1
min_sc_dp: 1
min_bulk_dp: 1
spikein_replicates: 100
hsnp_spikein_size: 40
hsnp_spikein_nsamples: 4000
gatk_chunks: 22
gatk_regions: 
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
chrs: 
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
scripts: /path/to/project/.snakemake/conda/<hash_value>/lib/scansnv
```

Do you have any ideas what might be going wrong here? Any suggestions what to try or what to check?

**Comment by jluquette** [comment]
Hi, sorry for not checking this issue tracker as often as I should.

That does seem like a strange error message. Could you also post the error you received when running the scansnv script (as a wrapper to snakemake)?

Were you able to run scansnv on the demo files?

**Comment by dlaehnemann** [comment]
Hi @jluquette,

thanks for checking in. The error received when just running the wrapper is simply a shorter version of the above error:
```
Building DAG of jobs...
InputFunctionException in line 59 of /path/to/project//.snakemake/conda/<hash_value>/lib/scansnv/Snakefile:
TypeError: must be str, not int
Wildcards:
gatk_mmq=60
gatk_chunk=1
```

I am also now trying it from scratch, once again copy-pasting your [instructions from the README.md](https://github.com/parklab/scan-snv#installing-scan-snv). Interestingly, this now throws a `Segmentation fault` during the installation of scansnv (inside the previously created `scansnv` environment):
```
$ conda install -c bioconda -c conda-forge/label/cf201901 -c jluquette scansnv
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done
Segmentation fault
```

No clue where that `Segmentation fault` comes from, but I do get it to work if instead of creating an environment first and then installing into it, I simply do both at the same time:

```
conda create -n scansnv -c bioconda -c conda-forge/label/cf201901 -c jluquette scansnv
```

Maybe that's a good alternative to document?

**Comment by jluquette** [comment]
That is very strange indeed--but I must admit I'm no conda expert and I have never had conda segfault during package installation. Are you sure the 'scansnv' env was completely deleted before you tried this?

And, in any case, thanks for the alternative solution. I'll add that to the README.

Once you do get scansnv installed, are you able to run the demo?

**Comment by dlaehnemann** [comment]
Your testing data runs through.

But trying to run it on a full dataset always gives the above error -- even if replicating the setup of your example run exactly (the exact command line argument setups and just one single cell bam). I tried all kinds of things with the parameters and even tried editing the respective rule in the Snakefile, but no luck. Do you have any ideas where the `str` vs. `int` conflict in that rule might come from?

**Comment by jluquette** [comment]
I do have one guess: the gatk_regions in your file happen to all be integers. Maybe this is causing config['gatk_regions'] to resolve to an int rather than a str in:

Snakefile:66-67
```
        regionflag=lambda wildcards:
            "-L " + config['gatk_regions'][int(wildcards.gatk_chunk) - 1],
```

To test, first try specifying just a single region on the command line like so:
`--regions 22:30000001-31000000`.

If that works, try modifying the above lines in the Snakefile to:
```
        regionflag=lambda wildcards:
            "-L " + str(config['gatk_regions'][int(wildcards.gatk_chunk) - 1]),
```

**Comment by tauanne** [comment]
I had the same error, and it was solved with your suggestion of specifying the regions, i.e. --regions 22:30000001-31000000. Thanks! 

Will the modification on Snakefile suggested imply that the algorithm will run for the entire chromosome as desired by me and, I suppose, also by the person who raised this issue?
Or is it necessary to specify the genomic positions of every chromosome of interest?

**Comment by jluquette** [comment]
I think the suggested modification will allow scansnv to run on a config file like @dlaehnemann used. I usually break the genome into finer chunks than chromosomes, so this issue never cropped up for me (e.g., see the gatk_regions_example.txt file for a breakdown of the autosomes into 300 chunks).

If @dlaehnemann gets back to us and it works, I'll commit the fix.

**Comment by dlaehnemann** [comment]
This does seem to be the culprit, so the fix you suggest should do the job.

As a side question: I had understood the default setting of `--abmodel-chunks 20` to mean, that each chromosome is split into 20 chunks per chromosome for the processing, and assumed that this also applies to the genotyping. Only now do I realise that this has to specified separately via a regions file. So the way to do such a splitting for the genotyping is to provide a regions file?

This should also provide a way of solving the classical GATK error of wrongly named chromosomes that has just cropped up, meaning I'll just have to prepend a `chr` to each line in your `gatk_regions_example.txt`. Thanks for pointing this file out.

**Comment by dlaehnemann** [comment]
Adding in the `chr` on the `--regions` command line argument or through the regions file then requires substituting all occurrences of `chr{chr}` in the Snakefile with `{chr}`, because otherwise filenames will e.g. contain a `chrchr22` and lead to file not found errors.

**Comment by jluquette** [comment]
Thanks for the feedback; I'll upload the fix. I'll try to answer your other questions and apologize in advance that the software is a little bit complicated.

1. Any option preceded by --abmodel is only relevant for the fitting process for the correlation functions. Additionally, there are two different "chunks" that go into AB model fitting. The first, which you've referenced here, only has to do with parallelizing the computation. The AB model parameters are fit by uniformly sampling from a large subset of the parameter space and approximating the likelihood function at each sample. The default is to sample 20,000 4-tuples. These 20,000 samples are broken up into 20 chunks and computed in parallel, if possible. Separating the sampling in this way does not cause approximation.

The other "chunk" type for AB model fitting is hSNP subwindows, specified by --abmodel-hsnp-chunk-size=N. This parameter causes each chromosome to be broken into non-overlapping windows of N hSNPs. The model likelihood is computed on each chunk independently and then multiplied together to approximate the chromosome-wide likelihood function. Smaller N means a less accurate approximation, but there is an O(N^2) compute cost.

And just to reiterate the first sentence: none of this applies to how GATK is run.

2. Re: adding "chr" to chromosome names. I've already fixed this for an internal project that was aligned to hg38. I will try to merge this all together and upload it today.

3. I just wanted to point out that in your config file above, the setting "fdr: 1.0" means an FDR of 100%, not 1%. This will not affect the p-values of the AB-model based tests, but the cutoffs used to determine if they pass will likely be meaningless.

**Comment by dlaehnemann** [comment]
Thanks for these clarifications. And now hurry on the uploading -- I patched my local version and have it running on a bigger dataset, now.

Also, thanks for pointing out the FDR setting. This is intended, as I wanted to start out with an unfiltered set of results and then compare against lower FDR values (probably something like 0.2, 0.1, 0.05, 0.01).

Also, I'll close this issue, as the original problem has been resolved. If other problems arise, I'll just create new specfic issues. Thanks again!

**Comment by jluquette** [comment]
Alright. I'm trying to wrap in some other updates so it'll take a little longer than I first thought.

If you want to test other FDRs, you can skip rerunning GATK, the phasing step and the very time consuming AB model fitting by simply renaming the "scansnv" directory in the output directory to anything other than scansnv (e.g., scansnv_fdr1.0) and then rerunning the pipeline. This will cause it to reuse all of the output in the abmodel, gatk and shapeit directories which are not at all affected by the FDR parameter.

If you have any questions about the software or results please feel free to ask here or via email. I'm happy to assist.
